- bliss/models/decoder.py
- bliss/models/encoder.py
- tests/test_m2.py
- tests/test_sleep_galaxy.py
I believe this will address the problem with galaxies looking different depending on the size of the ptile padding. It was the same issues with stars -- which I fixed earlier -- but I guess that fix didn't go through to galaxies. 
For future reference, the "rule of thumb" to keep things scale-invariant to image size is to always pass in the a source (either a psf or a rendered galaxy) to `._render_one_source` that is the same size as the padded tile (or whatever you're rendering the source on). If the original PSF or galaxy is too large, we should trim it; if it is too small, we pad it with zeros. 
Before merging, maybe @ismael-mendoza can checkout this branch and see if it indeed fixes those example images that you showed before? And of course double check if the rendering of galaxies …
> fix in galaxy scaling

- bin/train.py
- bliss/datasets/simulated.py
- bliss/models/galaxy_net.py
- bliss/sleep.py
- bliss/wake.py
Closes #145 
Does anybody know how to edit the fits file and get rid of this warning quickly? This is the only warning left when running tests - maybe @Runjing-Liu120 or @jeff-regier ?
```
tests/test_sdss.py::TestSDSS::test_sdss[0]
/Users/Ismael/miniconda3/envs/galsim/lib/python3.7/site-packages/astropy/wcs/wcs.py:466: FITSFixedWarning: RADECSYS= 'ICRS ' / International Celestial Ref. System 
the RADECSYS keyword is deprecated, use RADESYSa.
colsel=colsel)
```
> get rid of all warnings in pytest

- bliss/sleep.py
- config/dataset/single_tile.yaml
- tests/test_sleep_star.py
Error in fluxes are computed in the `get_metrics` method of SleepPhase, and fluxes are now tested in `test_star_sleep.py`.
> Bl test for fluxes sleep test

- bliss/models/decoder.py
- bliss/wake.py
- tests/test_wake.py
The WakePhase class should now be compatible with our most recent changes. I've also added a test for the wake-phase, which I can go over when we meet. We can discuss if what I have currently is the best way to test the wake-phase. 
In brief, the test
- runs the sleep phase to train the encoder
- picks an image, `obs_image`, from the original dataset (it picks one with the most stars)
- defines a new dataset with a perturbed PSF
- runs the wake-phase on `obs_image` and the trained encoder, with the perturbed PSF as an initialization. 
- checks if the wake-phase recovers the PSF in the original dataset (i.e. the PSF that constructed `obs_image`). 
I took out functions for background estimation for now. I'll make another pull request to add it back in. I think we need the background …
> Bl reviving wake phase

- .gitignore
- .pylintrc
- poetry.lock
- pyproject.toml
This PR adds pylint to our develop dependencies. It also includes a `.pylintrc` configuration file which suppresses a lot of useless warnings. Currently our code scores 7.77 / 10 for code quality -- pretty good. Pylint flags the following issues:
```
bliss-niKoUB-f-py3.8) regier@deeplearning-01:~/bliss$ pylint bliss/
************* Module bliss
bliss/__init__.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module bliss.plotting
bliss/plotting.py:1:0: C0114: Missing module docstring (missing-module-docstring)
bliss/plotting.py:4:0: C0103: Argument name "ax" doesn't conform to snake_case naming style (invalid-name)
bliss/plotting.py:4:0: C0103: Argument name "s" doesn't conform to snake_case naming style (invalid-name)
bliss/plotting.py:4:0: C0116: Missing …
```
> add pylint

- pytest.ini
Close #171 
Two warnings should be harmless. Add ignore in pytest.
> Ignore deprecation warning in `tests/test_tune.py`

- bliss/__init__.py
- bliss/datasets/simulated.py
- bliss/main.py
- bliss/models/decoder.py
- bliss/models/encoder.py
- bliss/sleep.py
- bliss/train.py
- bliss/tune.py
- config/dataset/cpu.yaml
- config/dataset/default.yaml
- config/dataset/m2.yaml
- config/dataset/single_tile.yaml
- config/dataset/test_plotting.yaml
- config/training/default.yaml
- config/tuning/m2.yaml
- tests/test_encoder_forward.py
- tests/test_generate.py
- tests/test_train.py
- tests/test_wake.py
close #179 
The `device` and `use_cuda` in `__init__.py` are completely removed to avoid dependencies on global `device` variable that is not managed by pytorch-lightning or config. To achieve this, the following changes are made (the following changes are tested both on gpu and cpu on our server.). 
- For tensors initialized in `__init__()`, they are now managed by pytorch itself to move together with the whole model using `register_buffer()`.
- For tensors created after `__init__()` in a downstream pass, their `device` is inferred from `self.device` which is updated whenever the model gets moved to a new device by pytorch-lightning.
- For tensors created for operating with "input", their `device` is inferred from the "input" tensor.
- [For tensors registered as …
> Remove `cuda` or `to` call

- bliss/__init__.py
This is what I came up with to solve #186.  We check if the user has BLISS_HOME in their environment. If they don't, we set it to a reasonable default (the directory of the loaded bliss module). This should work without changing code elsewhere.
> Set BLISS_HOME on module load if not already set

- .codecov.yml
- .pylintrc
- bliss/datasets/catsim.py
- bliss/datasets/sdss.py
- bliss/datasets/simulated.py
- bliss/generate.py
- bliss/main.py
- bliss/models/decoder.py
- bliss/models/galaxy_net.py
- bliss/sleep.py
- bliss/train.py
- bliss/tune.py
- bliss/wake.py
I made some minor changes to reduce the number of pylint warnings.
With these changes our code quality rating is 9.49 / 10. The following pylint warnings are still around:
```
+-----------------------------+------------+
|message id                   |occurrences |
+=============================+============+
|too-many-locals              |15          |
+-----------------------------+------------+
|too-many-arguments           |10          |
+-----------------------------+------------+
|import-outside-toplevel      |9           |
+-----------------------------+------------+
|fixme                        |8           |
+-----------------------------+------------+
|too-many-instance-attributes |6           |
+-----------------------------+------------+
|import-error                 |6 …
```
> fixes some pylint warnings

- .github/workflows/config.yml
Fixes the poetry-core package at version 1.0.0 in Github Actions. This is due to issue 3650 on the poetry Github repo (no direct link to avoid cross referencing on Github).
> Fix poetry-core=1.0.0 in github action 

- .github/workflows/config.yml
This adds caching of the poetry cache folder, which should greatly speed up subsequent runs on Github Actions.
The cache will be regenerated every time the poetry.lock file is changed. We actually don't need to do this, but we don't want this cache folder getting too big since Github has a 5GB limit on cache sizes.
> Cache Poetry Folder on Github Actions

- bliss/datasets/sdss.py
This closes #206 by suppressing the warning at the specific line.
This occurs when unpickling a FITS object.
> Suppress FitsFixedWarning on loading pickled FITS object

- tests/test_tune.py
Close #238 
I think we can safely ignore this as it is triggered by Raytune callback internally and we are not using model checkpointing.
> Fix model checkpoint warning

- bliss/models/encoder.py
- poetry.lock
- pyproject.toml
This PR refactors our tiling mechanism in `encoder.py`
The previous implementation uses an "identity" conv2d to make tiles, which requires ~50 lines of code and need to store a sparse weight matrix.
This new implementation uses 5 lines of code and might be more readable.
PS:
- We don't have to use `einops.rearrange` but I think it's more readable. I can change it to use the more standard chains of reshape and permute if you think `einops` is unnecessary.
- I haven't removed the old implementation so that I can assert that I don't accidentally change anything. If this looks good, I can remove the old ones and merge.
> Refactor tiling

- .pylintrc
- bliss/datasets/sdss.py
- bliss/metrics.py
- bliss/models/decoder.py
- bliss/models/encoder.py
- bliss/predict.py
- bliss/sleep.py
- bliss/wake.py
- config/config.yaml
- tests/test_tune.py
close #249
close #248 
This PR refactors `.view`, `.reshape`, `.squeeze`, `.sum`,  `.repeat` to `einops` counterparts except when:
- shapes were inferred somewhere else and it's already clear what each dimension represents. [example](https://github.com/prob-ml/bliss/blob/64d9f1138949ec8061ac7daf85d2f16c0a0d3faa/bliss/models/decoder.py#L392-L408)
- squeeze or unsqueeze for broadcasting. [example](https://github.com/prob-ml/bliss/blob/64d9f1138949ec8061ac7daf85d2f16c0a0d3faa/bliss/models/decoder.py#L184-L185) [example](https://github.com/prob-ml/bliss/blob/64d9f1138949ec8061ac7daf85d2f16c0a0d3faa/bliss/models/decoder.py#L234)
I disabled the "too many statements" pylint check so that I can make line-by-line assertions making sure I don't change anything. I'll remove the old implementation …
> Refactoring with Einops

- config/config.yaml
- config/dataset/default.yaml
- config/dataset/m2.yaml
- config/dataset/single_tile.yaml
- config/predict/sdss_basic.yaml
- poetry.lock
- pytest.ini
- tests/conftest.py
- tests/test_multi_gpu.py
This small PR introduces the changes that we discussed in our last meeting related to `CUDA_VISIBLE_DEVICES` flag. Assuming that everyone now sets this flag in their `.bashrc`, we now expect that the `gpus` flag of pytorch_lightning  be `1, 2, ...` depending on how many gpus to use (not their indices). 
This change has been propagated to `config/config.yaml` and  unit tests (where always 1 gpu is used). Any additional suggestions @ZachariahPang ?
> Cuda visible devices

- bliss/models/encoder.py
- bliss/sleep.py
- config/model/1galaxy_measure.yaml
- config/model/sleep_sdss_measure_simple.yaml
I realized that we only need to crop `tile_slen` instead of `2*tile_slen` in the `encoder.center_ptiles` function. 
Recall that in each padded tile which contains exactly one galaxy, we center the padded tile on that galaxy using the `grid_sample` function to train the galaxy encoder in the sleep phase. We decided to crop this "centered padded tile" in order to avoid sharp boundaries with 0s after the `grid_sample`. I thought that I needed to crop `2*tile_slen` on each side of this padded tile to avoid the sharp boundaries, but I realized I only need to crop half! The reason is that if a galaxy is at the border of a tile, the maximum distance it can be from the center of tile is `sqrt(2)/ 2 * tile_slen` which means that `grid_sample` only shifts the image by at most this quantity and …
> only need to crop = tile_slen not 2*tile_slen

- .github/workflows/stale.yml
Hey @jeff-regier I found this workflow which might be useful to manage our issues. It automatically flags stale issues and closes them if they don't get any activity after they have been flagged
> Add workflow to automatically flag stale issues

- bliss/train.py
- bliss/utils.py
- tests/test_train.py
This PR adds the ability to log custom information to all the loggers in `pl.trainer`. Currently, it logs `mode`, `gpus`, `training`, `model`, `dataset` and `optimizer` from `Hydra` config and the number of parameters in the model using `Tensorboard` in the file `hparams.yaml`.
---
Example `hparams.yaml` logged by Tensorboard from running `bliss mode=train`
- Master branch
```yaml
encoder:
n_bands: 1
tile_slen: 2
ptile_slen: 6
max_detections: 1
channel: 17
spatial_dropout: 0.11399
dropout: 0.013123
hidden: 185
decoder:
n_bands: 1
slen: 30
tile_slen: 2
ptile_slen: 6
prob_galaxy: 0.0
max_sources: 1
mean_sources: 0.015
min_sources: 0
f_min: 100000.0
f_max: 1000000.0
psf_params_file: data/sdss/94/1/12/psField-000094-1-0012.fits
background_values:
- 865.0
annotate_probs: false …
```
> Add custom loggiing to all loggers

- bliss/models/binary.py
- bliss/models/encoder.py
- bliss/models/galaxy_encoder.py
- bliss/predict.py
- bliss/sleep.py
- tests/test_m2.py
This refactors `get_full_params()` by splitting the functionality into smaller methods to disentangle what it does. Hopefully this will make it easier to maintain.
Another key change is that `get_full_params()` takes in only the `tile_slen` and infers the other variables (`slen`, `wlen`, etc). Before we were using `slen`, `wlen`, and the tile parameters to infer `tile_slen`. The latter was more complicated because we needed to check a lot of assertions (i.e. that `n_tiles_per_image` divided evenly into `slen**2`).
> Refactor get_full_params() 

- bliss/models/encoder.py
- bliss/predict.py
This change allows for get_full_params_from_tiles() to work
when the original image was not square. This fixes a bug in
predict.py introduced by the refactoring of get_full_params()
in 23fe0e4a5e2e0384d3991c8b930f93c0f3b5f0ad
> get_full_params_from_tiles(): Allow for non-square images

- .gitattributes
- bliss/datasets/sdss_blended_galaxies.py
- bliss/datasets/simulated.py
- bliss/models/decoder.py
- bliss/models/galaxy_encoder.py
- bliss/models/prior.py
- bliss/predict.py
- bliss/sleep.py
- bliss/train.py
- config/config.yaml
- config/training/sdss_autoencoder.yaml
- config/training/sdss_binary.yaml
- config/training/sdss_galaxy_encoder.yaml
- config/training/sdss_galaxy_encoder_real.yaml
- config/training/sdss_sleep.yaml
- models/Makefile
- models/convert_checkpoints.py
- models/run_experiment.sh
- models/sdss_autoencoder.ckpt
- models/sdss_autoencoder.pt
- models/sdss_binary.ckpt
- models/sdss_binary.pt
- models/sdss_galaxy_encoder.ckpt
- models/sdss_galaxy_encoder.pt
- models/sdss_galaxy_encoder_real.ckpt
- models/sdss_galaxy_encoder_real.pt
- models/sdss_sleep.ckpt
- models/sdss_sleep.pt
- tests/conftest.py
- tests/m2/m2.yaml
This change converts the stored model checkpoints for the sdss_galaxy project into state dicts. 
A PyTorch Lightning checkpoint stores everything associated with a model (initial arguments, optimizer state, state_dict), while a Torch state_dict is just the states of the trained parameters. Effectively, this means that the PL checkpoint is storing both configuration and state, while the Torch checkpoint is just storing state.
With the change to the Hydra config (#396), we can now just load the config with Hydra and only save the state of each trained object. These saved state_dict files take up much less space on disk, and now configuration is no longer hidden in the checkpoint file; all configuration is in the Hydra config.
> Convert model checkpoints to state dicts and utilize Hydra's instantiate

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- case_studies/sdss_galaxies/config/config.yaml
- case_studies/sdss_galaxies/main.py
- case_studies/sdss_galaxies/plots.py
- poetry.lock
- pyproject.toml
> Make paper images png

- README.md
- bliss/__init__.py
- case_studies/sdss_galaxies/main.py
- case_studies/sdss_galaxies/tests/conftest.py
- case_studies/sdss_galaxies/tests/test_generate.py
- case_studies/sdss_galaxies/tests/test_reporting.py
- case_studies/sdss_galaxies/tests/test_sdss.py
- tests/conftest.py
- tests/m2/conftest.py
- tests/m2/m2.yaml
- tests/m2/test_m2.py
- tests/m2/test_tune.py
Closes #361. This will greatly simplify the pathing issue, since the need to set BLISS_HOME is delegated out to the specific folder directory. Along with the recent improvements to the Hydra configs, this will make setting different data directories outside the BLISS codebase trivial. (e.g. set "paths.sdss" to "/data/sdss").
To figure out where testing data files are, tests will use their own `__file__` absolute path.
> Remove BLISS_HOME dependency and improve path configuration

- .isort.cfg
- .pre-commit-config.yaml
- bliss/encoder.py
- bliss/inference.py
- bliss/models/binary.py
- bliss/predict.py
- bliss/sleep.py
Fixes very annoying error when doing multi-line imports that basically makes committing impossible. 
Not sure if better to get rid of multi-line imports, but since the functions names are very explicit and long I think this is better.
> fixes isort/black clashing

- bliss/datasets/sdss.py
- bliss/datasets/sdss_blended_galaxies.py
- case_studies/sdss_galaxies/config/config.yaml
- case_studies/sdss_galaxies/tests/test_sdss.py
- case_studies/sdss_galaxies_vae/config/config.yaml
- case_studies/sdss_galaxies_vae/reconstruction.py
We aren't currently using the fetch bright stars functionality in SloanDigitalSkySurvey, so we can remove a lot of code in sdss.py. When we need that functionality again, we should bring it back as a separate class to keep loading the actual data as simple as possible.
Closes #381.
> Simplify SloanDigitalSkyDataset by removing bright stars functionality

- bliss/datasets/sdss_blended_galaxies.py
- bliss/encoder.py
- bliss/inference.py
- bliss/models/binary.py
- bliss/models/decoder.py
- bliss/models/galaxy_encoder.py
- bliss/models/location_encoder.py
- bliss/models/prior.py
- bliss/predict.py
- bliss/sleep.py
- tests/m2/test_m2.py
- tests/test_encoder_forward.py
Fixes #390. We now keep track of the padded tiles in their 2-D positions, which makes it easier to reconstruct non-square images.
> Split n_ptiles_per_image into n_tiles_h, n_tiles_w

- .gitignore
- data/sdss_all
It was a symbolic link that should not be included in the repo
> remove sdss all

- bliss/models/location_encoder.py
> Utilize square-root of background when log-transforming images

- bliss/datasets/simulated.py
- bliss/models/prior.py
- case_studies/sdss_galaxies/config/config.yaml
- case_studies/sdss_galaxies_vae/config/config.yaml
- tests/m2/m2.yaml
No longer hard-code the image size in ImagePrior. This makes it simpler and allows non-square images to be generated.
> Refactor ImagePrior to not hard-code slen

- .flake8
- bliss/train.py
- case_studies/sdss_galaxies/config/config.yaml
- case_studies/sdss_galaxies/tests/conftest.py
- case_studies/sdss_galaxies/tests/test_location_encoder.py
- case_studies/sdss_galaxies_vae/config/config.yaml
- case_studies/sdss_galaxies_vae/tests/conftest.py
- tests/conftest.py
- tests/m2/m2.yaml
- tests/star_basic/star_basic.yaml
Partially adddresses #485  (the first 3 errors listed)
Fixes the issue below by removing all `deterministic=True` usages in the codebase. I don't think we were relying on this for anything but please correct me if I'm wrong @dereklhansen , @jeff-regier. A seed can still be set via `training.seed`. 
```
E       RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```
> Fix location encoder test on gpu

- bliss/reporting.py
This fixes plot_locs() to expect locations in "pixel" units.
Previously, plot_locs() was expecting normalized locations (between 0 and 1),
which it then multipled by the slen of the image.
With the change to the FullCatalog class, we were passing it
"ploc" (pixel locations), which are already scaled to the size
of the image.
> Fix plotting bug in plot_locs()

- .gitattributes
I ran into some problems push my notebook so this fixes that. I only in nbstripout notebooks in my case_studies folder. @dereklhansen feel free to add your directly later too if that might be helpful for your own notebooks.
> nbstripout notebooks in `case_studies/sdss_galaxies/notebooks`

- bliss/models/location_encoder.py
- bliss/sleep.py
- tests/test_encoder_forward.py
I have in mind overhauling the location encoder more thoroughly (begun on branch `jr/deeper_refactoring`), but I'm not sure when I'll get to it, so we may as merge this now. It's already a significant simplification. Closes #388 more or less. In a deeper refactoring, I'd aim to get rid of `encode_for_n_sources` (and `encode_for_n_sources_flat`, and `_get_hidden_indices`) entirely.
> refactor location encoder

- bliss/catalog.py
- bliss/encoder.py
- bliss/inference.py
- bliss/models/galaxy_encoder.py
- bliss/models/location_encoder.py
- case_studies/sdss_galaxies/plots.py
- case_studies/sdss_galaxies_vae/reconstruction.py
- tests/case_studies/m2/test_m2.py
- tests/case_studies/sdss_galaxies_vae/test_sdss_blended_galaxies.py
This reverts commit 25f21f43f82185ca75463b3c457b7e368148e9fd.
There is a regression in the performance of the BinaryEncoder,
likely due to the way the images are pre-processed. We'll need
to debug this further.
> Revert "Enable sampling from variational distribution (#556)"

- bliss/models/location_encoder.py
This PR pretty much closes #540.
I didn't remove some of the masking that should be unnecessary because I was concerned about introducing bugs, and I wasn't sure if I could rely on our tests to catch any new bugs while #563 remains an issue.
There's still quite a bit more we could do to improve the readability of the location encoder. For instance, many of the calls to `rearrange` and `squeeze` could likely be avoided by not flattening structures in the first place. But this PR may be enough for now.
> more location encoder refactoring

- bliss/catalog.py
- bliss/encoder.py
- bliss/models/binary.py
- bliss/models/galaxy_encoder.py
- bliss/models/location_encoder.py
- tests/case_studies/m2/test_m2.py
- tests/test_encoder_forward.py
Closes #572.
This is toward #587 as well. Having a single ptile dimension will make it easier to move chunks on/off the GPU when the frame is too big to fit in GPU memory
> Use single dimension for ptiles in encoder (LocationEncoder, BinaryEncoder, GalaxyEncoder)

- .github/workflows/docs.yml
It looks like the recent crashes in our documentation were due to an update from the Github Action I was using to force-push to master-sphinx. I pinned this action at the last good commit.
> Fix documentation errors by pinning git push action

- bliss/encoder.py
- bliss/models/location_encoder.py
This refactors LocationEncoder to use the same logic for both sampling and variational mode (with the latter now a special case of the former).
> Make variational mode a special case of LocationEncoder.sample()

- .github/workflows/case_studies.yml
- tests/case_studies/sdss_galaxies/test_binary.py
GitHub CI times out after 6 hours. There doesn't appear to be an easy way to change this limit.
> run only pytest --gpu nightly; case studies takes too long

- bliss/catalog.py
- bliss/datasets/galsim_galaxies.py
- bliss/models/decoder.py
- bliss/reporting.py
- case_studies/sdss_galaxies/plots/autoencoder.py
- case_studies/sdss_galaxies/plots/sim_blend_metrics.py
- tests/case_studies/sdss_galaxies/test_decoder_ellipticity.py
- tests/case_studies/sdss_galaxies/test_galaxy_blend.py
> enable ellipticities in tile catalog and decoder

- .github/workflows/case_studies.yml
- .github/workflows/docs.yml
- .github/workflows/tests.yml
> fix workflow files

- case_studies/summer_template/config.yaml
- conf/base_config.yaml
- tests/basic_config.yaml
Reuse / extend `{BLISS_HOME}/conf/base_config.yaml` anywhere. Given following directory structure:
```sh
├── bliss
├── case_studies
│   └── summer_template
│       └── config.yaml
├── conf
│   └── base_config.yaml
└── tests
└── basic_config.yaml
```
we can set defaults in `conf/base_config.yaml` like so:
```yml
---
...
mode: train
paths:
root: ${oc.env:BLISS_HOME}
data: ${paths.root}/data
sdss: ${paths.data}/sdss
output: ${paths.root}/output
pretrained_models: ${paths.data}/pretrained_models
...
```
and override/augment variables in `case_studies/summer_template/config.yaml` like so:
```yml
---
defaults:
- ../../conf@_here_: base_config
- _self_
- override hydra/job_logging: stdout
paths:
project: ${paths.root}/case_studies/summer_template
output: ${paths.project}/output …
```
> Add base hydra config to be extended

- bliss/metrics.py
- tests/test_metrics.py
Fixes #752. Metrics didn't correctly handle the case when either the number of true or estimated sources in a batch was 0, and would raise an exception. Now we manually check before calling `match_by_locs` and increment false positives / false negatives accordingly. I don't think there's any good way of measuring "average distance" in this case since there are no matches to compute the distance between, so that only gets updated in batches that have both true and estimated sources.
Also added `test_no_sources` in test_metrics that checks this functionality.
> Fix metrics bug when 0 sources

- bliss/generate.py
- bliss/simulator/simulated_dataset.py
- case_studies/diskrw_gsimages_721/config.yaml
- conf/base_config.yaml
- tests/test_cached_dataset.py
- tests/testing_config.yaml
So that `cfg.cached_simulator` is only needed/used for training, and `cfg.generate` (with `cfg.simulator`) defines how data is generated at generate step.
> Decouple generate config from training

- bliss/generate.py
- tests/conftest.py
Get `cached_data_path` from `cfg.generate` instead of `cfg.cached_simulator` in generate.
https://github.com/prob-ml/bliss/blob/756092a0b1f14fe43890bf8f09eab238147d9ef6/bliss/generate.py#L19-L21
> Fix bug with cached_data_path in generate

- bliss/generate.py
- bliss/simulator/simulated_dataset.py
- tests/test_cached_dataset.py
Partially fix bug where each epoch runs `num_workers * n_batches + valid_n_batches` iterations when it should be `n_batches + valid_n_batches` iterations. Partial because bug would remain for `SimulatedDataset`.
Associated sanity-check test results ensuring similar validation losses / speed of the two approaches:
| dataset type                         | mappable | mappable | iterable | iterable |
| - | - | - | - | - |
| num workers                          | 0        | 32       | 0 | 32 |
| training loss (after 250 iterations) | 1.82     | 1.82     | 1.92 | 1.9 |
| val loss                             | 1.8513   | 1.8513   | 1.90651 | \- |
| speed (median it/s)                  | 4.98     | 1.4      | 4.92 | 3.98 |
> Make CachedSimulatedDataset mappable Dataset

- bliss/generate.py
- bliss/simulator/simulated_dataset.py
1) Logs config used at generation time to generated data folder for reference
2) Move asserts checking that all splits are present out of CachedSimulatedDataset constructor and into individual dataloader functions. This allows for having separate datasets used for training/testing, e.g. generating training data with certain params and test data with other params.
```
train_only_dataset = instantiate(cfg.cached_simulator, cached_data_path="path/to/train/data")
test_only_dataset = instantiate(cfg.cached_simulator, cached_data_path="path/to/test/data")
trainer.fit(encoder, datamodule=train_only_dataset)
trainer.test(encoder, datamodule=test_only_dataset)
trainer.fit(encoder, datamodule=test_only_dataset)
trainer.test(encoder, datamodule=train_only_dataset)
```
> Log generation parameters and allow loading cached dataset without all splits

- bliss/train.py
- conf/base_config.yaml
- tests/testing_config.yaml
Add option to stop training early if validation loss hasn't decreased for a set number of epochs. This is configurable using the `enable_early_stopping` and `patience` flags in `config.trainer`.
I removed the `min_epochs` flag from trainer because that overrides early stopping. I also suppressed a pylint warning for too-many-statements in `train` - we should maybe consider factoring some of the stuff that isn't directly related to training, like loading best weights, into a separate function.
> Add early stopping

- bliss/generate.py
- bliss/simulator/simulated_dataset.py
- case_studies/diskrw_gsimages_721/config.yaml
- conf/base_config.yaml
- scripts/generate_data_in_parallel.sh
- tests/testing_config.yaml
Either 
```
{BLISS_HOME}/generate_data_in_parallel.sh 32 0 {CONFIG_PATH}
```
or 
```
bliss -cp {CONFIG_PATH} 'mode=generate' 'generate.n_processes=32' 'generate.n_workers_per_process=0'
```
Some stats:
32 processes * 6 batches * 64 images/batch = **12,288 images** | **32 processes** | **0 workers/process**
- bash: 12454.65s user 113.11s system 2074% cpu 10:05.89 total
- python multiprocessing: 10617.55s user 74.27s system 934% cpu 19:03.68 total
1 process * 192 batches * 64 images/batch = **12,288 images** | **1 process** | **32 workers/process**
- bash: 7936.11s user 33.56s system 114% cpu 1:55:54.86  total
Fixes #761.
> Multi-process single-threaded data gen

- tests/test_sdss_reconstruct.py
- tests/test_simulate.py
It looks like some data structures weren't moved over to whatever device the encoder is on. As a result, though `pytest` passes, `pytest --gpu` wasn't passing before this PR.
> fixed tests on gpu

- bliss/metrics.py
- tests/test_metrics.py
`metrics.avg_distance` is the average distance over all matched objects, not just over those we consider a "good" match (i.e. distance < slack). This can be useful in the case where there are no good matches at all, but also having a measure of how good the good matches are would be useful.
> Add average_keep_distance metric for distance only on good matches

- case_studies/diskrw_gsimages_721/config.yaml
- scripts/generate_data_in_parallel.sh
Allow overriding hydra config parameters in `scripts/generate_data_in_parallel.sh`, and also add graceful exit.
> Allow config overrides in parallel generate script

- bliss/encoder.py
- bliss/metrics.py
- bliss/simulator/decoder.py
- tests/test_metrics.py
Added metrics for point estimates of galaxy parameters to make it easier to interpret model performance. Namely, we compute the median absolute error for `{disk/bulge}_flux`, `{disk/bulge}_q`, `{disk/bulge}_hlr` (half-light radius), and `beta_radians` between the estimated and true catalogs. Note that these metrics are only computed when these parameters are available in the true catalog, i.e. from the simulated data. 
Other changes:
- documented the galsim parameters in `decoder.render_galaxy`
- refactored `metrics.update` into two main functions, `_update_detection_metrics` (which contains the old metrics) and `_update_classification_metrics` (which is new and only gets called when classification metrics can be computed)
- add test for classification metrics
- speed up validation by …
> Metrics for galaxy parameters

- .github/workflows/docs.yml
Attempt to fix docs build error introduced by #786 - https://github.com/prob-ml/bliss/actions/runs/5250650821
> Unstage docs/docsrc/bin before commit and push

- poetry.lock
- tests/test_api.py
Make tests run faster. Part of the issue is because test_api now uses base_config and not testing_config, as the "base config". Ideally we would want to be able to use testing_config as the base config to bliss.api.BlissClient.
> Test API train on 1 epoch

- .github/workflows/tests.yml
Following [this](https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954), added codecov token to repo secrets and to CodeCov task yml, hopefully codecov doesn't fail as often anymore
> Add codecov token to github workflows yml

- bliss/catalog.py
- tests/test_catalogs.py
Added auxiliary functions to `TileCatalog` to
1) Restrict the catalog to the brightest source per tile (for when `max_sources > 1`), and
2) Filter the tile catalog by a given flux range.
`get_brightest_source_per_tile` returns a new `TileCatalog` where only the brightest "on" source per tile is kept. Effectively, this means that there are two conditions to fulfill: the source must have been "on" in the original catalog, and it must be brighter than the other sources (if any) in that tile. The tensors change in size from (b x nth x ntw x **max_sources** x k) to (b x nth x ntw x **1** x k), where b = batch size, nth x ntw is the dimension of an image in tiles, max_sources is the old maximum sources per tile, and k is the dimension of each parameter (e.g. 2 for locs). …
> Filter tile catalog by flux and restrict tile catalog to brightest source per tile

- tests/test_api.py
test_api.py now runs (locally) in ~1min. Fixes #828. Also fix #831.
> Remove dupe logic for tests implicitly run in fixture

- bliss/api.py
- bliss/catalog.py
- bliss/encoder.py
- bliss/plotting.py
- bliss/predict.py
- bliss/simulator/prior.py
- data/tests/multiband_data/dataset_0.pt
- data/tests/multiband_data/dataset_1.pt
- data/tests/sdss_preds.pt
- data/tests/test_multi_source.pt
- tests/conftest.py
- tests/test_api.py
- tests/test_encoder.py
- tests/test_metrics.py
- tests/test_sdss_reconstruct.py
- tests/test_simulate.py
Fixes #863, #864, #866, and #868.
Main changes:
- We now model the star fluxes in the variational distribution as a `LogNormal`, instead of modeling the log fluxes as a `Normal` distribution. This is consistent with galaxy fluxes, which are modeled as `LogNormal`.
- `plot_plocs` has been moved to `plotting.py`, and now accepts either a string or a list of indices to determine which sources to plot
- Added `plocs` to the astropy table returned in `api.fullcat_to_astropy_table`. This was missed initially since `plocs` isn't in the dictionary, so isn't found in `catalog.items()`.
Minor changes:
- Added tests for using the deconvolution/psf params to encode the psf, and for encoding a batch with multiple sources per tile.
- Modified some tests to use `encoder` and `decoder` fixtures
> Miscellaneous fixes

- .gitignore
- bliss/api.py
- bliss/catalog.py
- bliss/conf/base_config.yaml
- bliss/generate.py
- bliss/predict.py
- bliss/simulator/background.py
- bliss/simulator/decoder.py
- bliss/simulator/prior.py
- bliss/simulator/psf.py
- bliss/simulator/simulated_dataset.py
- bliss/surveys/decals.py
- bliss/surveys/sdss.py
- bliss/surveys/survey.py
- bliss/utils/download_utils.py
- tests/conftest.py
- tests/mock_tests.py
- tests/test_api.py
- tests/test_catalogs.py
- tests/test_generate.py
- tests/test_metrics.py
- tests/test_predict.py
- tests/test_sdss.py
- tests/test_sdss_reconstruct.py
- tests/test_simulate.py
- tests/testing_config.yaml
Generalize Bliss E2E flow to different surveys
Key idea is `image_id` now denotes the survey-specific image-identifying data structure that abstracts away survey-specific details from Bliss end-to-end generation, training, prediction functions.
However, the new change more tightly couples survey dataset (e.g., `SloanDigitalSkySurvey`) with its constituent/related modules `ImageDecoder`, `ImagePrior`, and `ImagePointSpreadFunction`; of note here is that `ImageDecoder` cannot now be as easily instantiated via `instantiate(cfg.simulator.decoder)` as before.
Fixes #853.
P.S. Tagged everyone because this is a large refactor that probably will touch some part of code that people have worked on before and are actively working on now.
> Generalize Bliss E2E flow to different surveys

- tests/test_predict.py
Remove tests that test mostly already-tested code.
Fixes #876.
> Reduce predict tests

- bliss/api.py
- bliss/conf/base_config.yaml
- bliss/simulator/simulated_dataset.py
- tests/test_api.py
Fixes #880. Parsing full slices ("0:80/80:90/90:100") was easier than relative values ("80/10/10") so I just went with this for now, since it allows for more flexibility anyway. Not sure if we need more sophisticated input validation - let me know if you think I should add it.
> Use percent slices for splits

- bliss/encoder.py
- bliss/unconstrained_dists.py
- tests/test_unconstained_dists.py
This PR fixes #692 and may help with #806. Perhaps surprisingly, the former pretrained weights still seem to work with this change.
> truncate location distribution in the unit box

- bliss/unconstrained_dists.py
`torch.Distribution` doesn't have a default `__repr__` apparently, so trying to print `TruncatedDiagonalMVN` fails with `NotImplementedError`. This PR just adds a simple `__repr__` that prints it similar to what it used to be before:
```
>>> print(pred["loc"])
TruncatedDiagonalMVN(Normal(loc: torch.Size([1, 18, 18, 2]), scale: torch.Size([1, 18, 18, 2])))
```
> Add repr to TruncatedDiagonalMVN class

- bliss/unconstrained_dists.py
- tests/test_unconstained_dists.py
Another quick fix for `TruncatedDiagonalMVN` - I think we need the CDF for #806 to evaluate the probability that a source is within the interior region,
$$q_\phi(z^{(i)}) = \mathbb{I}[z^{(i)} = \varnothing](1 - q_{\phi_i}(y_i = 1)\mathbf{q_{\phi_i}(\ell_i \in R_i)}) + \mathbb{I}[z^{(i)} \neq \varnothing]q_{\phi_i}(z^{(i)})$$
In code this first term would translate to
```
loss += (true_cat.n_sources == 0) * (1 - on_prob * (pred["loc"].cdf([0.95, 0.95]) - pred["loc"].cdf([0.05, 0.05]))
```
> Add CDF for TruncatedDiagonalMVN

- bliss/encoder.py
We used to use the wrong band for loss computation when using a single band due to `enumerate` not giving us the right indices. Instead, we now iterate over `self.bands` instead to ensure we're using the right index into the flux tensors.
Also, I added small constants in the `log_prob` for `LogNormal` distributions to ensure that the value is in the support (>0). The old code worked because our generated data has values in each tile, even if it contains no sources, but this is more robust anyway. The values where this is needed will get masked out anyway, we just need to make sure it doesn't produce a `nan` since that won't get masked properly.
> Use correct band for loss computation when not using all bands

- poetry.lock
- pyproject.toml
pip doesn't support galsim 2.4.7 anymore, so we're upgrading to the latest version 2.4.10.
> Update galsim version

- README.md
- poetry.lock
- pyproject.toml
Renaming bliss PyPI package to `bliss-toolkit`, and upgrading to version 0.2.2 in preparation for 0.3 release.
> Rename PyPI package to bliss-toolkit

- bliss/encoder.py
- bliss/predict.py
Previously, `get_input_tensor` modified `batch` in-place to add an extra dim. This is annoying as `batch` can't be used again without squeezing out the extra dim. Instead, we now use a view of the original tensor instead (this is more efficient than making a copy, and since the current code doesn't modify any of the data itself, should be safe to do).
> Don't modify batch in get_input_tensor

- bliss/metrics.py
- case_studies/adaptive_tiling/region_encoder.py
Fixes #915.
I remembered the main issue with metrics wasn't the predicted catalog, it was that the true catalog is a `RegionCatalog` and we don't have a good way of converting it to a `TileCatalog` for the conditional tile-based metrics. Since we care more about detection metrics with the region encoder, I just used the `FullCatalog`-based metrics instead.
> Compute metrics during training with RegionEncoder

- pyproject.toml
Only change after v0.3 PyPI version is fixes to GMM model load warning, so have just tagged latest status as v0.3.
> Update BLISS version to 0.3

- bliss/predict.py
- bliss/surveys/decals.py
- bliss/surveys/des.py
- bliss/surveys/sdss.py
- tests/test_catalogs.py
- tests/test_metrics.py
- tests/test_sdss.py
Added binary variable `load_image_data` that conditionally loads real survey image data only when it is needed (e.g., in predict).
NOTE: DES image data is currently loaded for DECaLS data simulation because the parameter `sig1` used for DECaLS coadd PSF simulation uses this image data for its computation. This dependence likely can be easily removed.
Fixes #907.
> Don't load real images when simulating data

- data/tests/decals/ccds-annotated-decam-dr9-small.fits
- scripts/prune_decam_ccds_annotated.py
- tests/conftest.py
- tests/test_decals.py
> Prune large DECam CCDs PSF params file

- case_studies/adaptive_tiling/region_catalog.py
- tests/test_catalogs.py
Previously, when converting a `TileCatalog` to a `RegionCatalog` we would just discard it if the conversion would produce a region catalog with multiple sources in one tile. Now, we instead keep the highest flux source and turn off all others in that tile.
The high-level algorithm is as follows:
```
1. Create a unique integer index for each region
2. Unfold with a 3x3 kernel with padding=1 and stride=2 to get number of sources and integer indices in each 3x3 tile
3. Determine which tiles have more than one source and the integer index of those regions
4. For each problematic tile:
- Get the flux of all "on" sources
- Find the integer index of the region with the highest flux
- Turn off all regions in the tile (for simplicity)
- Turn the max flux region back on
```
> Filter region catalog by flux per tile when converting from tile catalog

- bliss/catalog.py
- bliss/cli.py
- bliss/conf/base_config.yaml
- bliss/encoder.py
- bliss/generate.py
- bliss/predict.py
- bliss/surveys/sdss.py
- bliss/train.py
- case_studies/api/api.py
- case_studies/api/test_api.py
- case_studies/decals_e2e_871/config_train.yaml
- case_studies/dependent_tiling/config.yaml
- case_studies/dependent_tiling/m2.ipynb
- case_studies/diskrw_gsimages_721/config.yaml
- case_studies/psf_variation/psf_variation_demo.ipynb
- case_studies/summer_template/config.yaml
- pyproject.toml
- tests/conftest.py
- tests/test_dc2.py
- tests/test_generate.py
- tests/test_predict.py
- tests/test_train.py
- tests/testing_config.yaml
With this PR each of our three top-level methods (`generate`, `train`, and `predict`) only receives the subset of the config parameters that are relevant to it.
> more modular config file

- case_studies/galaxy_clustering/config.yaml
- case_studies/galaxy_clustering/data_generation/DES_data_extraction.py
- case_studies/galaxy_clustering/data_generation/galsim-des.yaml
- case_studies/galaxy_clustering/encoder/encoder.py
- case_studies/galaxy_clustering/encoder/metrics.py
- case_studies/galaxy_clustering/encoder/variational_dist.py
- case_studies/galaxy_clustering/notebooks/PredictionTest.ipynb
- case_studies/galaxy_clustering/prior.py
- Subclassed `VariationalDist` to sample `BaseTileCatalog` instead of `TileCatalog`
- Removed catalog matching from metrics and retained only cluster membership in variational factors and metrics
- Omit `sample_image_renders` in `on_validation_epoch_end`
- Preliminary prediction notebook
- Calibrate prior pixel scale with DES pixel scale
> GalaxyClusterEncoder simplification and DES calibration

- bliss/simulator/decoder.py
Every time drawImage() called, the folding_threshold (originally defaulted set to 0.995) is lowered to 0.95 if the average flux across bands is lower than a dim threshold. Use to speed up the drawing process.
> Speeding up drawImage by reducing folding_threshold for galaxies with dim fluxes

- bliss/encoder/variational_dist.py
had to re-fix the gating error after recent changes, now convergence (or anything of size (b, h, w, 1)) is correctly squeezed before being gated even in the absence of n_sources
> re-fix of old silent error (loss shape broadcast mismatch caused by extra dim of size 1)

- bliss/encoder/image_normalizer.py
- case_studies/galaxy_clustering/encoder/convnet.py
Realized that the normalizer used the sliced image as output instead of the original image. Fixed this issue. Since we were getting OOM errors, had to resort to using a mix of stride 4 and stride 2 in our downsampling layers.
> Quick Bug Fix

- bliss/cached_dataset.py
Minor update to #1075.
The sorted list of file names returned by `sorted(os.listdir(str(self.cached_data_path)))` might have a meaningful order. For example, DC2 split files have a non-random ra/dec order when listed alphanumerically. As a result, if we split the cached data files into train/val/test based on the order in which they appear in `sorted(os.listdir())`, the assignment is not random with respect to ra/dec (or any other variable that determines their order).
To fix this, we randomly shuffle the list of files after loading them in. `random.shuffle()` is seeded by `pl.seed_everything()`, so it will be reproducible across any training runs that set the same seed.
This fix probably won't matter for most case studies, but it's helpful for weak lensing because we use our test set …
> Randomly shuffle cached data files when loading them in
