bliss/models/encoder.py
bliss/sleep.py

The map estimate methods can now take in multiple images at once

Bl vectorized map estimates

---

config/training/cpu.yaml
config/training/default.yaml
config/training/m2.yaml
config/training/test_plotting.yaml
config/training/unittest.yaml
requirements.txt

we don't use pillow/optuna/h5py

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

added ray and pre-commit to poetry dev dependencies

---

case_studies/starnet/m2_results.ipynb

Reviving the M2 notebook here. 
@ZachariahPang , you may find some of the plotting functions I used helpful, and let me know if you have any questions.

starnet notebook

---

config/config.yaml
tests/conftest.py
tests/test_galaxy_detection.py
tests/test_galaxy_vae.py
tests/test_sdss.py
tests/test_sleep_star.py

Adds a configurable path for SDSS in Hydra

Add configurable path for SDSS in Hydra 

---

bliss/datasets/sdss.py
poetry.lock
pyproject.toml
tests/test_sdss.py

This removes the FITSIO dependency and refactors the SDSS PSF code a bit to be more object-oriented

Removes FITSIO dependency from SloanDigitalSkySurvey 

---

pytest.ini
tests/test_tune.py

Fix test tune

---

bliss/generate.py
bliss/main.py
bliss/predict.py
bliss/train.py
bliss/tune.py
tests/test_generate.py
tests/test_predict.py
tests/test_train.py
tests/test_tune.py

Give more descriptive names to four functions which were named `main`.
closes #222

main -> predict, train, tune, generate

---

bliss/datasets/sdss.py

This refactors the stamping part of the SDSS package into its own class, enabling its use in other areas.

Separate SDSS Stamping code into StarStamper class

---

bliss/generate.py
bliss/models/encoder.py
bliss/plotting.py
bliss/sleep.py
bliss/train.py
config/dataset/toy_gaussian.yaml
config/model/sleep_1galaxy_1star.yaml
poetry.lock
pyproject.toml
tests/test_sleep_binary.py

Implements various metrics/plots which will be useful for evaluating galaxy/star misclassification issues.

Misclassification accuracy

---

bliss/models/binary.py
bliss/models/galaxy_encoder.py
bliss/sleep.py
config/training/test_plotting.yaml
tests/test_plotting.py

I also fix a small error that causes `test_tune.py` to fail in the GPU

quick fix on plotting coverage

---

.pre-commit-config.yaml

darglint precommit

---

.github/workflows/tests.yml

Update Codecov Github Action to v2

---

bliss/train.py

Automatically create output directory if it doesn't already exist

---

bliss/models/decoder.py
case_studies/sdss_galaxies/config/config.yaml
tests/m2/m2.yaml

Remove unneeded prob_galaxy argument from ImageDecoder

---

bliss/models/location_encoder.py
bliss/predict.py
bliss/sleep.py
tests/m2/test_m2.py

remove prob_n_sources

---

bliss/datasets/simulated.py
bliss/encoder.py
bliss/inference.py
bliss/models/decoder.py
bliss/models/galaxy_encoder.py
case_studies/sdss_galaxies/plots.py
case_studies/sdss_galaxies_vae/config/config.yaml
case_studies/sdss_galaxies_vae/config/reconstruct/sdss_figures_real.yaml
case_studies/sdss_galaxies_vae/reconstruction.py
case_studies/sdss_galaxies_vae/tests/test_reconstruction.py

This allows inference on non-square images within `inference.py`.

Allow for inference on non-square images

---

bliss/reporting.py
case_studies/sdss_galaxies/plots.py
case_studies/sdss_galaxies_vae/reconstruction.py

Refactor plotting

---

bliss/encoder.py
bliss/inference.py
bliss/models/location_encoder.py
case_studies/sdss_galaxies/plots.py
case_studies/sdss_galaxies_vae/reconstruction.py

Use tile catalog throughout inference and find galaxy blends

---

bliss/reporting.py
case_studies/sdss_galaxies/config/config.yaml
case_studies/sdss_galaxies/plots.py
case_studies/sdss_galaxies_vae/reconstruction.py

plotting improvements

---

bliss/reporting.py
case_studies/sdss_galaxies_vae/reconstruction.py

Allow for manual application of masks to saturated SDSS areas

---

bliss/models/decoder.py
bliss/models/location_encoder.py
bliss/models/prior.py
case_studies/sdss_galaxies/config/config.yaml
case_studies/sdss_galaxies_vae/config/config.yaml
tests/case_studies/m2/m2.yaml
tests/case_studies/m2/test_m2.py
tests/case_studies/sdss_galaxies/test_galaxy_prior.py
tests/star_basic/star_basic.yaml

Fix GalaxyPrior not using correct dataset

---

bliss/catalog.py
bliss/inference.py
bliss/reporting.py
case_studies/sdss_galaxies/plots.py

I also set `mag_slack = 1.0` by default in light of separating detection from magnitude metrics.

fix two important errors in indexing when computing metrics

---

bliss/reporting.py
case_studies/sdss_galaxies/notebooks/frame-plotly.ipynb
case_studies/sdss_galaxies/plots.py
case_studies/sdss_galaxies_vae/reconstruction.py

Did I miss anything @dereklhansen ?

Fix coadd params shift

---

bliss/reporting.py

Fix matching algorithm by adding sharp penalty for points far away

---

.github/workflows/tests.yml
bliss/catalog.py
bliss/datasets/background.py
bliss/datasets/galsim_galaxies.py
bliss/datasets/sdss_blended_galaxies.py
bliss/datasets/simulated.py
bliss/generate.py
bliss/inference.py
bliss/models/binary.py
bliss/models/decoder.py
bliss/models/galaxy_net.py
bliss/models/location_encoder.py
bliss/models/prior.py
bliss/reporting.py
bliss/train.py
case_studies/sdss_galaxies/config/config.yaml
case_studies/sdss_galaxies_vae/config/config.yaml
poetry.lock
pyproject.toml

Add MyPy static type checking

---

.pre-commit-config.yaml
bliss/catalog.py
poetry.lock
pyproject.toml

closes #528 and upgrades pytorch to version 1.9 (all tests pass on the gpu now)

upgrade pytorch; pre-commit runs mypy

---

bliss/datasets/sdss.py

Shift PHOTO plocs by 0.5 to be consistent

---

bliss/datasets/sdss_blended_galaxies.py
bliss/encoder.py
bliss/inference.py
bliss/models/galaxy_encoder.py
bliss/models/galaxy_net.py
bliss/models/location_encoder.py
bliss/models/vae/galaxy_vae.py
tests/case_studies/m2/test_m2.py
tests/test_encoder_forward.py

max_a_post -> variational_mode

---

bliss/encoder.py
bliss/inference.py
case_studies/sdss_galaxies/plots.py
case_studies/sdss_galaxies_vae/reconstruction.py

Allow Encoder to handle entire frame and remove ChunkedScene

---

bliss/datasets/galsim_galaxies.py
tests/case_studies/sdss_galaxies/test_galaxy_blend.py

This is the last step we need before #456

add blendedness

---

bliss/models/galsim_encoder.py

Add Galsim galaxy encoder

---

bliss/models/lensing_binary_encoder.py

Add lensing binary encoder

---

bliss/models/lens_encoder.py

Add lensing encoder

---

case_studies/coadds/coadd_decoder.py
case_studies/coadds/config/config.yaml
tests/case_studies/coadds/test_coadd_decoder.py

Hi @wangmallory here are some changes I forgot from our meeting yesterday. Does it look good to you ?

small changes to coadd decoder

---

bliss/models/detection_encoder.py
case_studies/coadds/config/config.yaml
case_studies/psf_homogenization/config/config.yaml
case_studies/sdss_galaxies/config/config.yaml
case_studies/sdss_galaxies_vae/config/config.yaml
case_studies/strong_lensing/config/config.yaml
tests/case_studies/m2/m2.yaml
tests/star_basic/star_basic.yaml
tests/test_encoder_forward.py

Remove mean sources attribute from detection encoder

---

.github/workflows/publish.yml
.github/workflows/tests.yml
.gitignore
README.md
bliss/catalog.py
bliss/datasets/galsim_galaxies.py
bliss/models/prior.py
case_studies/sdss_galaxies_vae/config/config.yaml
case_studies/strong_lensing/config/config.yaml
pyproject.toml
tests/case_studies/sdss_galaxies_vae/test_galaxy_vae.py

add workflow to publish bliss when a new version is released
- Remove ToyGaussian as it it's no longer  useful
- Update README to at least mention bliss is pip installable

make bliss pip installable 

---

.github/workflows/case_studies.yml

I think this should fix the comment from Jeff in #711

no pipx in case study workflow

---

.gitignore
.pre-commit-config.yaml
bliss/catalog.py
bliss/encoder.py
bliss/inference.py
bliss/models/detection_encoder.py
bliss/models/galaxy_encoder.py
bliss/models/galaxy_net.py
bliss/models/prior.py
bliss/plotting.py
bliss/reporting.py
bliss/train.py
case_studies/coadds/get_results.py
case_studies/galsim_galaxies/get_figures.py
case_studies/sdss_galaxies/get_figures.py
case_studies/sdss_galaxies_vae/reconstruction.py
case_studies/starnet/plotting.py
poetry.lock
pyproject.toml
tests/case_studies/galsim_galaxies/test_reporting.py
tests/case_studies/m2/test_m2.py
tests/test_encoder_forward.py

I made these refactoring changes while I was comparing encoders architectures. I think it's clearest if I put these refactoring changes in their own PR and merge it before making substantive changes to the encoder.

refactoring in preparation to remove tiling

---

bliss/encoder.py

Some code copied over from @XinyueLi1012's `xl/reconTest` branch.
This PR changes `variational_mode(...)` to return point estimates for galaxy parameters too.

galsim point estimates

---

bliss/simulator/decoder.py

Cleaned up the code in `decoder.py` to simplify the functions used to generate the PSF, and add more documentation about what each function is doing.
Main changes:
- combining `forward_psf_from_params` and some of the processing in the constructor into a single function, `_get_psf`
- making `_get_mgrid` no longer static, and removing the scaling factor at the end (since it was un-scaled immediately in the constructor, canceling it out) 
- changing self.params from a Parameter to a buffer
Comparing the PSF generated by the current changes to the one generated by the old version, there are minor differences (on the order of 10^-12), but I think those are just due to imprecision with floating point operations. 
Please take a look and let me know if these changes seem reasonable - I'm only …

Refactor decoder to simplify PSF construction

---

bliss/simulator/decoder.py
bliss/simulator/prior.py
bliss/surveys/sdss.py
conf/base_config.yaml

Add asserts with more descriptive error messages to check that files exist before loading, and fix wrong default fields in base_config

Change default fields in base_config; assert paths exist when loading

---

tests/test_end_to_end.py
tests/testing_config.yaml

save predict.html in the temporary directory and delete it after testing

avoid create new file when tesing plot

---

tests/test_api.py
tests/testing_config.yaml

Fix warnings with tests

---

.github/workflows/tests.yml
bliss/utils/download_utils.py
tests/test_api.py

Don't connect to SDSS remote server in test

---

scripts/generate_data_in_parallel.sh

Re-added the option to specify `config-path` and `config-name` (Hydra args) for the generate script. Having this option is useful when you need to change many different parameters.
The usage is now `generate_data_in_parallel.sh -n NUM_PROCESSES [-cp CONFIG_PATH] [-cn CONFIG_NAME] [CONFIG_OVERRIDES]`. The `num-processes` flag is required, but `config-path` and `config-name` are optional - they will use the default in `api.main` if not specified. Individual overrides can still be specified positionally.

Allow specifying config file again in generate script

---

bliss/api.py
tests/test_api.py

Took way too long to fix this than I should've (lol)
Test:`pytest tests/test_api.py -k "predict or table"`
Fixes #838.

Fix bug in table conversion from torch.squeeze

---

bliss/api.py
bliss/encoder.py
bliss/predict.py
bliss/surveys/sdss.py
tests/test_api.py
tests/test_metrics.py

Addresses #821, but only for SDSS.

Convert fluxes to nmgy after prediction

---

bliss/api.py

Really small change. See tutorial.ipynb diff for side-by-side.

Make est_cat_table more slightly more readable

---

bliss/predict.py
bliss/surveys/des.py
bliss/surveys/sdss.py
data/des/336/3366m010/tractor-3366m010.fits
tests/test_predict.py
tests/test_train.py

Finishing up DES E2E, less support for `plot_predict` due to mismatch in total number of available band-pass filters.

Test DES predict (without plotting SDSS/DECaLS "true" catalogs)

---

bliss/conf/base_config.yaml

This PR sets the default validation check during training to be for every 1 epoch rather than 10.

Check validation every 1 epoch

---

bliss/conf/base_config.yaml
bliss/predict.py
bliss/surveys/decals.py
bliss/surveys/des.py
bliss/surveys/sdss.py
bliss/surveys/survey.py
tests/test_predict.py
tests/test_sdss.py
tests/test_train.py

Fix DES/DECaLS warnings

---

bliss/predict.py
bliss/simulator/decoder.py
bliss/surveys/decals.py
bliss/surveys/des.py

Final fixes for v0.3. Also improves coadd depth-wise alignment but not completely—will address post-v0.3.

Fix flux calibrations for DES/DECaLS

---

bliss/surveys/decals.py
bliss/surveys/des.py
bliss/surveys/survey.py

Multiplying real image data by conversion ratio to get data in `nelec` physical units.

Bugfix: DES/DECaLS image data in nelec

---

bliss/surveys/decals.py

Fix DECaLS load PSF params warnings

---

case_studies/redshift_estimation/prior.py

Small tweak; changed naming of priors but left the "dummy" Uniform prior there for testing purposes.

Adding Jacky's Gamma prior to `dm/redshift_estimation` branch.

---

case_studies/redshift_estimation/prior.py

Add prior for galaxy reading from csv

Update prior.py for galaxy prior

---

bliss/encoder/plotting.py
case_studies/redshift_estimation/commands.txt
case_studies/redshift_estimation/prior.py
case_studies/redshift_estimation/redshift.yaml

Changes to classes in `prior.py` to properly sync up redshift and photometry. Adding sample notebook that shows how to access checkpoints and perform a first-pass evaluation on the training data.

Changes to redshift/photometry priors and notebook for sample evaluation.

---

bliss/conf/base_config.yaml
bliss/encoder/data_augmentation.py
bliss/encoder/image_normalizer.py
bliss/simulator/simulated_dataset.py
bliss/surveys/dc2.py
bliss/surveys/sdss.py
case_studies/adaptive_tiling/config.yaml
case_studies/catalog_comparison/catalog_comparison.ipynb
case_studies/catalog_comparison/config.yaml
case_studies/dc2/config.yaml
case_studies/dc2/train_dc2.sh
case_studies/multi_source_per_tile/config.yaml
case_studies/multiband/alignment.ipynb
case_studies/psf_variation/config.yaml
case_studies/psf_variation/evaluate_models.ipynb
case_studies/psf_variation/psf_variation_demo.ipynb
case_studies/psf_variation/train_models.sh
tests/test_dc2.py
tests/test_encoder.py
tests/test_simulate.py
tests/testing_config.yaml

Removed deconvolved image functionality during generation and training. The `psf_variation` case study still has some references to old functionality but I need to update that anyway with other changes so I'm leaving it for the other PR.

Removed deconvolution

---

bliss/encoder/encoder.py

This PR creates a new method of `Encoder` called `initialize_networks` to load the CNNs. By overriding the `initialize_networks` method in a subclass of `Encoder`, any network architecture can be substitute for the current one.
@kapnadak @gapatron

initialize CNNs in dedicate method

---

bliss/encoder/unconstrained_dists.py

I couldn't find a TruncatedNormal in torch.distribitutions.  There was a truncnormal in torch.nn.init, but it couldn't handle multiple means and stdevs.  So I just sampled with inverse cdf.

sample from truncated normal without rejection sampling

---

tests/test_main.py
tests/test_simulator.py

Oops, I neglected to include these tests in my previous PR.

missing tests

---

bliss/conf/base_config.yaml
case_studies/prior_elicitation/flux_prior.ipynb
case_studies/psf_variation/config.yaml
case_studies/spatial_tiling/toy_example.yaml

This PR makes the prior parameters more suitable for SDSS.

sdss-like prior
